// Card previews render ~400px wide, so let the browser pick the 800px copy from public/thumbs
// (generated by `npm run thumbs`) instead of decoding the 1600px original.
export const CARD_IMAGE_SIZES = '(max-width: 720px) 85vw, (max-width: 1080px) 50vw, 33vw';

export function cardSrcSet(src) {
  if (!src.endsWith('.webp')) return undefined;
  return `/thumbs${src} 800w, ${src} 1600w`;
}
